pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                echo 'Cloning repository...'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'pip install -r requirements.txt'
            }
        }
        stage('Check Python') {
            steps {
                bat '"C:\\Users\\Vishal\\AppData\\Local\\Programs\\Python\\Python310\\python.exe" --version'
            }
        }
        stage('Run Test') {
            steps {
                bat '"C:\\Users\\Vishal\\AppData\\Local\\Programs\\Python\\Python310\\python.exe" tests/test.py'
            }
        }
        stage('Build Complete') {
            steps {
                echo 'Build Successful 🚀'
            }
        }
    }
}
